global:
  jfrogUrl: "http://artifactory-local.my-arti.svc.cluster.local:8082"
  versions:
    worker: 1.216.0
  imagePullSecrets:
    - mysecret
  imageRegistry: myregistry.com
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
