global:
  masterKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  joinKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

nginx:
  tlsSecretName: artifactory-tls

artifactory:
  customSecrets:
    - name: custom-secret
      key: custom-secret.yaml
      data: >
        secret data
  customVolumes: |
    - name: custom-secret
      secret:
        secretName: custom-secret