jfrogUrl: "http://artifactory-local.my-arti.svc.cluster.local:8082"

extraVolumes:
  - name: custom-trust-store
    secret:
      secretName: catalog-custom-truststore

extraVolumeMounts:
  - name: custom-trust-store
    mountPath: /usr/share/extras
    readOnly: true