global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  generateSelfSignedCert: true

artifactory:
  circleOfTrustCertificatesSecret: edge-root-crt
