global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  generateSelfSignedCert: true
  service:
    type: LoadBalancer
    loadBalancerSourceRanges:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    externalTrafficPolicy: Local