{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "indexer")) "true") (.Values.indexer.autoscaling.enabled) (eq .Values.indexer.autoscaling.keda.enabled true) (.Values.indexer.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-indexer
  {{- if or .Values.global.autoscaling.keda.annotations .Values.indexer.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.indexer.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-indexer
  minReplicaCount: {{ .Values.indexer.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.indexer.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.indexer.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.indexer.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.indexer.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.indexer.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesIndexer" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "persist")) "true") (.Values.persist.autoscaling.enabled) (eq .Values.persist.autoscaling.keda.enabled true) (.Values.persist.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-persist
  {{- if or .Values.global.autoscaling.keda.annotations .Values.persist.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.persist.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-persist
  minReplicaCount: {{ .Values.persist.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.persist.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.persist.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.persist.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.persist.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.persist.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesPersist" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "analysis")) "true") (.Values.analysis.autoscaling.enabled) (eq .Values.analysis.autoscaling.keda.enabled true) (.Values.analysis.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-analysis
  {{- if or .Values.global.autoscaling.keda.annotations .Values.analysis.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.analysis.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-analysis
  minReplicaCount: {{ .Values.analysis.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.analysis.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.analysis.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.analysis.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.analysis.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.analysis.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesAnalysis" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "policyenforcer")) "true") (.Values.policyenforcer.autoscaling.enabled) (eq .Values.policyenforcer.autoscaling.keda.enabled true) (.Values.policyenforcer.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-policyenforcer
  {{- if or .Values.global.autoscaling.keda.annotations .Values.policyenforcer.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.policyenforcer.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-policyenforcer
  minReplicaCount: {{ .Values.policyenforcer.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.policyenforcer.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.policyenforcer.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.policyenforcer.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.policyenforcer.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.policyenforcer.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesPolicyenforcer" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.sbom.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "sbom")) "true") (.Values.sbom.autoscaling.enabled) (eq .Values.sbom.autoscaling.keda.enabled true) (.Values.sbom.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-sbom
  {{- if or .Values.global.autoscaling.keda.annotations .Values.sbom.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.sbom.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-sbom
  minReplicaCount: {{ .Values.sbom.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.sbom.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.sbom.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.sbom.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.sbom.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.sbom.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesSbom" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.aiscanner.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "aiscanner")) "true") (.Values.aiscanner.autoscaling.enabled) (eq .Values.aiscanner.autoscaling.keda.enabled true) (.Values.aiscanner.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-aiscanner
  {{- if or .Values.global.autoscaling.keda.annotations .Values.aiscanner.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.aiscanner.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-aiscanner
  minReplicaCount: {{ .Values.aiscanner.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.aiscanner.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.aiscanner.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.aiscanner.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.aiscanner.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.aiscanner.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesAiscanner" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.reporting.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "reporting")) "true") (.Values.reporting.autoscaling.enabled) (eq .Values.reporting.autoscaling.keda.enabled true) (.Values.reporting.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-reporting
  {{- if or .Values.global.autoscaling.keda.annotations .Values.reporting.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.reporting.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-reporting
  minReplicaCount: {{ .Values.reporting.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.reporting.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.reporting.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.reporting.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.reporting.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.reporting.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesReporting" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (or .Values.jascontextual.enabled .Values.jas.separate.service.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "jascontextual")) "true") (.Values.jascontextual.autoscaling.enabled) (eq .Values.jascontextual.autoscaling.keda.enabled true) (.Values.jascontextual.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-jascontextual
  {{- if or .Values.global.autoscaling.keda.annotations .Values.jascontextual.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.jascontextual.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-jascontextual
  minReplicaCount: {{ .Values.jascontextual.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.jascontextual.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.jascontextual.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.jascontextual.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.jascontextual.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.jascontextual.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesJasContextual" . | indent 4 }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (or .Values.jasexposures.enabled .Values.jas.separate.service.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "jasexposures")) "true") (.Values.jasexposures.autoscaling.enabled) (eq .Values.jasexposures.autoscaling.keda.enabled true) (.Values.jasexposures.autoscaling.keda.queues) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-jasexposures
  {{- if or .Values.global.autoscaling.keda.annotations .Values.jasexposures.autoscaling.keda.annotations }}
  annotations:
    {{- with .Values.global.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.jasexposures.autoscaling.keda.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "xray.fullname" . }}-jasexposures
  minReplicaCount: {{ .Values.jasexposures.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.jasexposures.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.jasexposures.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.jasexposures.autoscaling.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
        {{- .Values.jasexposures.autoscaling.keda.scaleUp | toYaml | nindent 10 }}
        scaleDown:
        {{- .Values.jasexposures.autoscaling.keda.scaleDown | toYaml | nindent 10 }}
  triggers:
  {{- include "xray.autoscalingQueuesJasExposures" . | indent 4 }}
{{- end }}
