{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "indexer")) "true") (.Values.indexer.autoscaling.enabled) (eq .Values.indexer.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-indexer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-indexer
  minReplicas: {{ .Values.indexer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.indexer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.indexer.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "persist")) "true") (.Values.persist.autoscaling.enabled) (eq .Values.persist.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-persist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-persist
  minReplicas: {{ .Values.persist.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.persist.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.persist.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "analysis")) "true") (.Values.analysis.autoscaling.enabled) (eq .Values.analysis.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-analysis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-analysis
  minReplicas: {{ .Values.analysis.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analysis.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analysis.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (ne (include "xray.service.kedaJobsEnabled" (list . "policyenforcer")) "true") (.Values.policyenforcer.autoscaling.enabled) (eq .Values.policyenforcer.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-policyenforcer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-policyenforcer
  minReplicas: {{ .Values.policyenforcer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.policyenforcer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.policyenforcer.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.sbom.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "sbom")) "true") (.Values.sbom.autoscaling.enabled) (eq .Values.sbom.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-sbom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-sbom
  minReplicas: {{ .Values.sbom.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sbom.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sbom.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.aiscanner.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "aiscanner")) "true") (.Values.aiscanner.autoscaling.enabled) (eq .Values.aiscanner.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-aiscanner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-aiscanner
  minReplicas: {{ .Values.aiscanner.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.aiscanner.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.aiscanner.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (.Values.reporting.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "reporting")) "true") (.Values.reporting.autoscaling.enabled) (eq .Values.reporting.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-reporting
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-reporting
  minReplicas: {{ .Values.reporting.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.reporting.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reporting.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (or .Values.jascontextual.enabled .Values.jas.separate.service.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "jascontextual")) "true") (.Values.jascontextual.autoscaling.enabled) (eq .Values.jascontextual.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-jascontextual
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-jascontextual
  minReplicas: {{ .Values.jascontextual.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.jascontextual.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.jascontextual.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (or .Values.jasexposures.enabled .Values.jas.separate.service.enabled) (ne (include "xray.service.kedaJobsEnabled" (list . "jasexposures")) "true") (.Values.jasexposures.autoscaling.enabled) (eq .Values.jasexposures.autoscaling.keda.enabled false) }}
  {{- if semverCompare ">=v1.23.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "xray.fullname" . }}-jasexposures
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "xray.fullname" . }}-jasexposures
  minReplicas: {{ .Values.jasexposures.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.jasexposures.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.jasexposures.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
