global:
  jfrogUrl: http://art-artifactory:8082
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

containerSecurityContext:
  enabled: false
podSecurityContext:
  enabled: false

rbac:
  create: true
serviceAccount:
  create: true

rabbitmq:
  auth:
    password: changeme
  rbac:
    create: true
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

postgresql:
  auth:
    password: changeme
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  serviceAccount:
    enabled: true
