apiVersion: v2
appVersion: 1.262.51
dependencies:
- name: jfrog-common
  repository: https://charts.jfrog.io/
  version: 0.0.9
description: A Helm chart for JFrog Bridge
home: https://jfrog.com/platform/
keywords:
- bridge
- jfrog
maintainers:
- email: infra@jfrog.com
  name: Chart Maintainers at JFrog
name: bridge
sources:
- https://github.com/jfrog/charts
type: application
version: 101.262.52
