global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  generateSelfSignedCert: true

artifactory:
  extraSystemYaml:
    shared:
      logging:
        consoleLog:
          enabled: true