unifiedUpgradeAllowed: true

distribution:
  jfrogUrl: "http://artifactory-local.my-arti.svc.cluster.local:8082"

common:
  customVolumes: |
    - name: custom-truststore
      configMap:
        name: custom-truststore
  customVolumeMounts: |
    - name: custom-truststore
      mountPath: /tmp/custom-truststore
      readOnly: true