unifiedUpgradeAllowed: true

distribution:
  jfrogUrl: "http://artifactory-local.my-arti.svc.cluster.local:8082"

postgresql:
  enabled: false

database:
  type: postgresql
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://my-external-postgres.example.com:5432/distribution"
  user: distribution
  password: "changeme"