global:
  jfrogUrl: "https://my-platform.example.com"

artifactory:
  access:
    accessConfig:
      security:
        tls: true
  nginx:
    http:
      enabled: false
    tlsSecretName: nginx-tls-secret

xray:
  enabled: true
  router:
    tlsEnabled: true
    serviceRegistry:
      insecure: true

distribution:
  enabled: true
  router:
    tlsEnabled: true
    serviceRegistry:
      insecure: true