global:
  jfrogUrl: "https://my-platform.example.com"

artifactory:
  artifactory:
    customPersistentVolumeClaim:
      name: artifactory-plugins
      mountPath: /var/opt/jfrog/artifactory-plugins
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: standard
