global:
  jfrogUrl: "http://artifactory-local.my-arti.svc.cluster.local:8082"
  versions:
    bridge: 1.262.47
  imagePullSecrets:
    - mysecret
  imageRegistry: myregistry.com
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb