apiVersion: v1
kind: Secret
metadata:
  name: systemyaml
type: Opaque
stringData:
  system.yaml: |
    shared:
      security:
        masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE