apiVersion: v1
kind: Service
metadata:
  name: {{ include "wingman.fullnamectx" (dict "Release" $.Release "Chart" $.Chart "Values" $.Values "serviceName" $.Values.service.name) }}
  labels:
    {{- include "wingman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-router
      port: {{ .Values.router.externalPort }}
      targetPort: {{ .Values.router.externalPort }}
      protocol: TCP
    - name: http-router-in
      port: {{ .Values.router.internalPort }}
      targetPort: {{ .Values.router.internalPort }}
      protocol: TCP
  selector:
    {{- include "wingman.selectorLabels" . | nindent 4 }}
