global:
  jfrogUrl: "https://my-platform.example.com"

artifactory:
  artifactory:
    extraSystemYaml:
      shared:
        logging:
          consoleLog:
            enabled: true

xray:
  xray:
    extraSystemYaml:
      shared:
        logging:
          consoleLog:
            enabled: true

distribution:
  enabled: true
  distribution:
    extraSystemYaml:
      shared:
        logging:
          consoleLog:
            enabled: true
