global:
  jfrogUrl: "http://art-artifactory:8082"
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

rabbitmq:
  auth:
    username: admin
    password: changeme

postgresql:
  auth:
    password: changeme

