global:
  jfrogUrl: "https://my-platform.example.com"
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

artifactory:
  nginx:
    generateSelfSignedCert: true
  artifactory:
    circleOfTrustCertificatesSecret: edge-root-crt