global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  generateSelfSignedCert: true

postgresql:
  auth:
    password: "<your-strong-password>"