global:
  jfrogUrl: "https://my-platform.example.com"

artifactory:
  artifactory:
    customSecrets:
      - name: custom-secret
        key: custom-secret.yaml
        data: >
          secret data
    customVolumes: |
      - name: custom-secret
        secret:
          secretName: custom-secret

xray:
  common:
    customSecrets:
      - name: custom-secret
        key: custom-secret.yaml
        data: >
          secret data
