artifactory:
  customPersistentVolumeClaim:
    name: artifactory-plugins
    mountPath: /var/opt/jfrog/artifactory-plugins
    accessModes:
      - ReadWriteMany
    size: 10Gi
    storageClassName: nfs
