global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  generateSelfSignedCert: true

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true