nginx:
  https:
    enabled: false

artifactory:
  customSecrets:
    - name: custom-secret
      key: custom-secret.yaml
      data: >
        secret data
  customVolumes: |
    - name: custom-secret
      secret:
        secretName: custom-secret
