global:
  masterKey: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

nginx:
  tlsSecretName: nginx-tls-secret

artifactory:
  primary:
    javaOpts:
      xms: "1g"
      xmx: "4g"