{{- if and (eq .Values.rtfs.enabled true) (eq .Values.rtfs.database.type "postgresql") }}
{{- if and (not .Values.rtfs.database.secrets) (not .Values.artifactory.unifiedSecretInstallation) }}
{{- if or .Values.rtfs.database.url .Values.rtfs.database.user .Values.rtfs.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory-ha.fullname" . }}-rtfs-database-creds
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- with .Values.rtfs.database.url }}
  rtfs-db-url: {{ tpl . $ | b64enc | quote }}
  {{- end }}
  {{- with .Values.rtfs.database.user }}
  rtfs-db-user: {{ tpl . $ | b64enc | quote }}
  {{- end }}
  {{- with .Values.rtfs.database.password }}
  rtfs-db-password: {{ tpl . $ | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
