annotations:
  category: AIInfrastructure
apiVersion: v2
appVersion: 0.606.22
dependencies:
- name: jfrog-common
  repository: https://charts.jfrog.io/
  version: 0.0.9
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.jfrog.io/
  version: 16.7.26
description: A Helm chart for JFrog Wingman.
keywords:
- wingman
- jfrog
kubeVersion: '>= 1.21.0-0'
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: wingman
sources:
- https://github.com/jfrog/charts
type: application
version: 100.606.22
