{{- if and (.Values.splitXraytoSeparateDeployments.fullSplit) (or .Values.jasexposures.enabled .Values.jas.separate.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "xray.fullname" . }}-jasexposures-headless
  labels:
    app: {{ template "xray.fullname" . }}
    chart: {{ template "xray.chart" . }}
    component: {{ .Values.xray.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    servicename: jasexposures
    {{- with .Values.xray.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  clusterIP: None
  type: ClusterIP
  {{- if .additionalSpec }}
{{ tpl .additionalSpec $ | indent 2 }}
  {{- end }}
  ports:
  - name: http-router
    port: {{ .Values.router.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.router.internalPort }}
  - name: http-jasexp
    port: {{ .Values.jasexposures.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.jasexposures.internalPort }}
  selector:
    app: {{ template "xray.name" . }}
    component: {{ .Values.xray.name }}
    release: {{ .Release.Name }}
    servicename: jasexposures
{{- end }}
