artifactory:
  haDataDir:
    enabled: true
    path: /var/opt/jfrog/artifactory-ha/data
  haBackupDir:
    enabled: true
    path: /var/opt/jfrog/artifactory-ha/backup
  coldStorage:
    enabled: true
