artifactory:
  ingressGrpc:
    enabled: true
    name: grpc
    hosts:
      - grpc.artifactory.example.com
    className: "nginx"
    grpcPath: /com.jfrog
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: GRPCS
    tls:
      - secretName: artifactory-grpc-tls
        hosts:
          - grpc.artifactory.example.com
