artifactory:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/artifactory-s3-access"
    automountServiceAccountToken: true
  rbac:
    create: true
    role:
      rules:
        - apiGroups:
            - ""
          resources:
            - services
            - endpoints
            - pods
          verbs:
            - get
            - watch
            - list
